@startuml

interface GearBox {
    + String gearBoxChangingUp()
    + String gearBoxChangingDown()
}

class GearBoxAdapter implements TransmissionBehaviour {

    - GearBox gearBox

    + GearBoxAdapter(GearBox gearBox)

    + String gearShiftUp()

    + String gearShiftDown()
}

class NormalGearBox implements GearBox {

    + String gearBoxChangingUp()

    + String gearBoxChangingDown()
}

class SportsGearBox implements GearBox {

    + String gearBoxChangingUp()

    + String gearBoxChangingDown()
}

@enduml