@startuml

class CarLocation implements Subject {
    - List<Observer> observers
    - double longitude
    - double latitude

    + CarLocation(List<Observer> observers)

    + void register(Observer observer)

    + void unregister(Observer observer)

    + void notifyObservers()

    + double getLongitude()

    + void setLongitude(double longitude)

    + double getLatitude()

    + void setLatitude(double latitude)

    + int carObserverCount()
}

class LocationObserver implements Observer {
    - double longitude
    - double latitude
    Subject carLocation

    LocationObserver(Subject carLocation)

    + void update(double longitude, double latitude)

    + String getCarLocation()
}

interface Observer {
    void update(double longitude, double latitude);
}

interface Subject {
    void register(Observer observer)
    void unregister(Observer observer)
    void notifyObservers()
}

@enduml