@startuml

class AccelerationState implements State {

    Car car
    + AccelerationState(Car car)

    + String turnKeyToStartEngine()

    + String accelerateCar()

    + String brakeCar()

    + String turnKeyToStopEngine()
}

class OffState implements State{

    Car car
    + OffState(Car car)

    + String turnKeyToStartEngine()

    + String accelerateCar()

    + String brakeCar()

    + String turnKeyToStopEngine()
}

class OnState implements State {

    Car car

    + OnState(Car car)

    + String turnKeyToStartEngine()

    + String accelerateCar()

    + String brakeCar()

    + String turnKeyToStopEngine()
}

interface State {
    String turnKeyToStartEngine()
    String accelerateCar()
    String brakeCar()
    String turnKeyToStopEngine()
}

@enduml