@startuml

abstract class Driver {

    - String name;

    + Driver(String name)

    + String drive()

    + abstract String accelerate()

    + abstract String brake()

    + String getName()

    + void setName(String name)
}

class ExperiencedDriver extends Driver{

    + ExperiencedDriver(String name)

    + String accelerate()

    + String brake()
}

class NewLearnerDriver extends Driver{

    + NewLearnerDriver(String name)

    + String accelerate()

    + String brake()
}

@enduml